### ISSUE TITLE
Add pyproject.toml support 

### ISSUE THREAD

**Issue by 3x10RaiseTo8** [JoshuaC215/agent-service-toolkit#13]

**Comment by 3x10RaiseTo8** [comment]
[Here](https://github.com/JoshuaC215/agent-service-toolkit/pull/14#issuecomment-2307384297) is the owner's comment.
I messed up with the renaming and deleting branches, oops.

@JoshuaC215, I have couple of questions.
1. Why not use the latest Pydantic as they already maintain v1 namespace in v2 package? During my initial try, uv was getting stuck since LangSmith (dependency by langchain_community) depends on Pydantic v2 and FastAPI <0.100 depends on Pydantic v1. Its a mess to say the least. But as long as the application is running fine, its alright, right?
2. Above raises a question that why we require FastAPI to be <0.100. I have tested in my personal projects that as long as you stick to v1 namespace, the docs generation works just fine.
3. Can you share a bit more about python <3.12.4 requirement?
4. Can you share why you pinned minor versions most of the packages?

**Comment by 3x10RaiseTo8** [comment]
Makes sense. Thank you! :smile:

**Comment by JoshuaC215** [comment]
I made some progress yesterday on adding `pyproject.toml` and getting some updated installation instructions that work, and using it in CI + docker builds.

I kept `requirements.txt` for now since it's still a bit confusing and doesn't work as easily as I want (due to the same issues I mentioned above). Hopefully langchain v0.3 will ship soon and it'll be an easy update from there.

Issues to watch on langchain v0.3: 
https://github.com/langchain-ai/langchain/discussions/19339
https://github.com/langchain-ai/langchain/discussions/24405

I want to get a lock file working (mostly likely with `uv lock`) before loosening the version restrictions on various libraries and fully removing `requirements.txt`.

**Comment by 7sunstudio** [comment]
All dependency errors are gone after the following update:

 dependencies = [
     "duckduckgo-search ~=6.2.6",
-    "fastapi <0.100.0",
+    "fastapi ~=0.114.2",
     "httpx~=0.26.0",
-    "langchain-core ~=0.2.26",
-    "langchain-community ~=0.2.11",
-    "langchain-openai ~=0.1.20",
-    "langchain-groq ~=0.1.9",
+    "langchain-core ~=0.3",
+    "langchain-community ~=0.3",
+    "langchain-openai ~=0.2",
+    "langchain-groq ~=0.2",
     "langgraph ~=0.2.3",
     "langgraph-checkpoint ~=1.0.2",
     "langgraph-checkpoint-sqlite ~=1.0.0",
     "langsmith ~=0.1.96",
     "numexpr ~=2.10.1",
-    "pydantic ~=1.10.17",
+    "pydantic ~=2.7.4",
     "pyowm ~=3.3.0",
     "python-dotenv ~=1.0.1",
     "setuptools ~=74.0.0",

**Comment by JoshuaC215** [comment]
Ya I saw the langchain v0.3 just released a couple days ago 🙌 

That's awesome to hear. Will give the upgrade a spin in the next few days

**Comment by JoshuaC215** [comment]
This has now been fixed in #35 😁 I'm very happy!

**Comment by 3x10RaiseTo8** [comment]
I guess, we can now loosen up the version restrictions now

**Comment by JoshuaC215** [comment]
Did you have a specific use case in mind for that or just generally think it’s better?

Either way feel free to open a PR :)
