### ISSUE TITLE
Load previous session

### ISSUE THREAD

**Issue by antonioalegria** [JoshuaC215/agent-service-toolkit#52]
Would be interesting to add loading the conversation history if re-using a thread ID from a previous session. It would basically require adding a service endpoint to get the history and then calling that in the beginning to populate it.

A separate issue would be to have the list of threads, like in ChatGPT.

**Comment by JoshuaC215** [comment]
Cool idea! I think it would be a significant change and tough to generalize. Also won’t work with the demo app since I don’t have a persisted db running today. Open to a contribution here but would need to be pretty neatly abstracted and not add to core complexity. Not sure I will have time to work on it.

**Comment by antonioalegria** [comment]
Sure. I was thinking adding a service endpoint that would get the history for a thread id, basically all of the messages and the current state, and then it would draw them in the app. This would be called first instead of drawing the placeholder first message.

**Comment by JoshuaC215** [comment]
Ah nice - yeah maybe it would be straightforward - feel free to share a pull request :)

**Comment by peterkeppert** [comment]
I already have this implemented for my project along the lines of @antonioalegria 's suggestion. So I did a quick port to agent service toolkit to see what would need to be done.

For now I added Chat ID to the sidebar, so that user can copy it and use it to share the chat like this: http://localhost:8502/?thread_id=c45ba586-31e3-4a22-9858-207f89830436 . Once such chat from history is opened, you can continue conversation in that thread.

![image](https://github.com/user-attachments/assets/801582dc-5c8b-4cda-ae78-e698b64b66c2)

**Comment by antonioalegria** [comment]
Any reason to use Chat ID instead of Thread ID?

**Comment by peterkeppert** [comment]
Not really, just overlooked this relic of my implementation, I updated the pull request to consistently use Thread ID

**Comment by JoshuaC215** [comment]
Thanks again for adding this @peterkeppert and @antonioalegria for the suggestion!
